### ISSUE TITLE
save settings

### ISSUE THREAD

**Issue by anonymous555** [kimsey0/Advisor#4]
Whenever hdt updates, it loses the settings for this plugin.  Save settings in a way that work across updates.

**Comment by chWolfgang** [comment]
I would second this. :) please.

**Comment by kimsey0** [comment]
I've noticed it myself too, but since I only change the overlay position, it wasn't enough of an irritant for me to try to fix. Now that I have this fork, I'll give it a go.

**Comment by kimsey0** [comment]
This should be fixed in https://github.com/kimsey0/Advisor/releases/tag/v1.0.14. Give it a go and let me know if it works for you.

**Comment by anonymous555** [comment]
I get this now.  

Make sure you are using the latest version of the Plugin and HDT.

System.ArgumentException: Item has already been added. Key in dictionary: 'AdvisorSettingsProvider'  Key being added: 'AdvisorSettingsProvider'
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Collections.Hashtable.Add(Object key, Object value)
   at System.Configuration.Provider.ProviderCollection.Add(ProviderBase provider)
   at System.Configuration.SettingsProviderCollection.Add(ProviderBase provider)
   at HDT.Plugins.Advisor.AdvisorSettingsProvider.Apply()
   at HDT.Plugins.Advisor.AdvisorPlugin.<OnLoad>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by anonymous555** [comment]
A bunch of regressions, I'm sticking with release 13.  

In 14, you lost a setting that was in 13 for removing played cards.

Also  Next to the title instead of showing 3/3 matching cards, it shows 3/30.

**Comment by BernsteinA** [comment]
3/30 is correct

**Comment by anonymous555** [comment]
It depends on how you do the accounting, and this is a change that's not what some folks want.

Knowing that 3 of 4 cards played matched tells you more information.

3/30 could mean 100% matches (3/3) or it could mean 50% (3/6) matches of cards played so far ... you just don't know.

**Comment by BernsteinA** [comment]
3 non-matching cards would show 3/33 not 3/30. The percentages (and the
underlying math) have not changed.
