### ISSUE TITLE
[again] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by icetbr** [kimsey0/Advisor#5]
```
22:03:20|Error|Advisor.ImportMetastatsDecks >> System.NullReferenceException: Object reference not set to an instance of an object.
   at HDT.Plugins.Advisor.Services.MetaStats.SnapshotImporter.<GetClassDecks>d__10.MoveNext() in C:\Users\Jacob\Documents\Git\Advisor\Advisor\Services\MetaStats\SnapshotImporter.cs:line 139
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HDT.Plugins.Advisor.Services.MetaStats.SnapshotImporter.<ImportDecks>d__8.MoveNext() in C:\Users\Jacob\Documents\Git\Advisor\Advisor\Services\MetaStats\SnapshotImporter.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HDT.Plugins.Advisor.Advisor.<ImportMetastatsDecks>d__23.MoveNext() in C:\Users\Jacob\Documents\Git\Advisor\Advisor\Advisor.cs:line 361

```

**Comment by chWolfgang** [comment]
I am getting this error as well.
I have also gotten it in the past from time time. It seems to come and go as the website updates itself. It may have something to do with that.

**Comment by Atmosf3ars** [comment]
Same for me, now I get always this error.
@kimsey0 Could you please have a look into this issue?

Thanks and kind regards

**Comment by icetbr** [comment]
I'm starting to give a stab at this error, but I don't do C#. The first 3 days I had available I managed to install Visual Studio :-) I tried to use VSCode, but it did not work. Progress will be slow on my end, but I'll attempt to use data from hsreplay, which uses JSON.

**Comment by chWolfgang** [comment]
This would be fantastic if you can pull it off. I miss this and getting data from HSreplay would be nice. TY for your efforts.

**Comment by icetbr** [comment]
Here you go

https://github.com/icetbr/Advisor/releases/tag/1.1.0

**Comment by chWolfgang** [comment]
Thank you VERY much.
I tried for a game or so and it works great. Kept my settings and everything!

**Comment by sarumans** [comment]
> Here you go
> 
> https://github.com/icetbr/Advisor/releases/tag/1.1.0



if i use new with hsreplay:
in some match import wrong deck (ex. hl hunter instead of mage etc)

**Comment by icetbr** [comment]
Here is the new version

https://github.com/icetbr/Advisor/releases/download/1.2.0/Advisor.zip

**Comment by sarumans** [comment]
WOW thaaaaanks a lot!!!!!


Il dom 12 lug 2020, 13:00 icetbr <notifications@github.com> ha scritto:
